name: dadjokes
version: 3.1.0
description: A collection of terrible jokes.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  share: ^2.0.4
  auto_size_text: ^3.0.0-nullsafety.0
  google_fonts: ^2.1.0

  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: e48abe7c3e9ebfe0b81622167c5201d4e783bb81

dev_dependencies:
  flutter_lints: ^1.0.3
  flutter_launcher_icons: ^0.9.0

flutter:
  uses-material-design: true
  assets:
   - assets/title-image.png

# On changing the icons below, run:
#   flutter packages run flutter_launcher_icons:main
# to update the various Android and iOS assets
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/source-icon.png"
  adaptive_icon_background: "assets/source-background.png"
  adaptive_icon_foreground: "assets/source-foreground.png"
